### ISSUE TITLE
[Build Failed]

### ISSUE THREAD

**Issue by PhoenixPeca** [RAKwirelessDev/rakwireless-docs#2]
the issue started with commit https://github.com/RAKwirelessDev/rakwireless-docs/commit/abf23905435a08f3ae50471e60a899930dfc5fa7

please be take extra caution before pushing. make sure that everything compiles before committing to master.

debugging must be done locally (use the CLI-command below):

```
vuepress build docs
```

**Comment by PhoenixPeca** [comment]
Hi All, It seems that the compiler is having so many untraceable errors due to logic errors in the config files. I'd like to introduce some points to be followed in creating a maintainable doc:

- Avoid editing the configs unless we are intending to add/change a site-wide setting. Especially not when we are editing configs just to fix a sidebar for a single page. Changes in the configs must be generalized to all pages.
- Unless really necessary, use only markdown syntax for formatting the page.
- If HTML is unavoidable, try to implement it as a "component" for reusability.

**Comment by PhoenixPeca** [comment]
Here are my thoughts:

- Can we try to get rid of the sidebar javascript configs and just use Markdown on the page? I think we can achieve this rather easily because vuepress automatically creates a sidebar table of contents based on the title headers.
- Can we try to compact the information of a single product in a SINGLE page rather than divide this infos in multiple URLs? We can do this with unification for each QuickStart and DataSheet pages. This method is very limiting for the users' perspective if they intend to print all information in a one-run since they have to open each link manually.

**Comment by drichardcarl** [comment]
> Hi @MarkNambatac @drichardcarl @aeraterta , It seems that the compiler is having so many untraceable errors due to logic errors in the config files (mainly due to edits in the sidebar configs and the plugins). I'd like to introduce some points to be followed in creating a maintainable doc:
> 
> * Avoid editing the configs unless we are intending to add/change a site-wide setting. Especially not when we are editing configs just to fix a sidebar for a single page. Changes in the configs must be generalized to all pages.
> * Unless really necessary, use only markdown syntax for formatting the page.
> * If HTML is unavoidable, try to implement it as a "component" for reusability.
> 
> Please take note that while vuepress is a very flexible platform, it does come at a cost of complexity. **More moving parts means harder to maintain thus more prone to errors.** Let's try to keep things tidy and simple as much as possible.
> 
> Also, I've been getting errors with vuepress even for empty setups.. This is probably a vuepress developers' fault as well. No worries though, vuepress will be due for a new release in the coming few days this month.

Hello @PhoenixPeca  can you attach here the image or link regarding these "errors" that you say here? We created a separate branch **docs-dev** where we commit our local/on-going changes. Before I merge the changes to **master**, I always run `yarn run docs:build` to see if it builds without errors, and try to host locally the built static files to see if everything is what as we expected -- which includes the navbar, sidebars, contents, etc.
